name: arquetipo_flutter_bloc
description: Arquetipo Atsistemas BLOC

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: ^5.0.2
  cupertino_icons: ^1.0.0
  device_preview: ^1.1.0
  dio: ^5.0.3
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^9.0.0
  go_router: ^11.1.3
  intl: ^0.18.0
  json_annotation: ^4.3.0
  json_serializable: ^6.6.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.18
  audio_video_progress_bar: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.2
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  retrofit_generator: ^8.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "res/images/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#000001"
  windows:
    generate: true
    image_path: "res/images/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "res/images/icon/icon.png"


flutter:
  generate: true

  
  uses-material-design: true

  
  assets:
    - res/images/
   
  
  fonts:
     - family: Proxima Nova
       fonts:
         - asset: res/fonts/Proxima Nova Black.otf
         - asset: res/fonts/Proxima Nova Bold.otf
         - asset: res/fonts/Proxima Nova Extrabold.otf
         - asset: res/fonts/Proxima Nova Thin.otf
         - asset: res/fonts/ProximaNova-Regular.otf
        
  